site_name: Learning Cocos2d
theme: readthedocs

pages:
- Home: "index.md"
- Hello World!: "helloworld.md"
- Hallo Hörnchen: "hellohoernchen.md"

markdown_extensions:
- footnotes
- admonition

- smarty:
    smart_quotes: False
- pymdownx.tasklist

repo_url: https://github.com/kantel/cocos2d

edit_uri: blob/master/docs

site_dir: "/Applications/MAMP/htdocs/cocos2d"


extra_css: [css/user.css]

extra_javascript: ["http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"]
